-- LogSense AI: Table Definitions
-- Creates the PARSED_LOGS table for storing parsed log entries.

USE DATABASE KAFKA_LOGS;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE PARSED_LOGS (
    LOG_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    APP_NAME VARCHAR(256),
    TIMESTAMP VARCHAR(64),
    LOG_LEVEL VARCHAR(10),
    COMPONENT VARCHAR(256),
    MESSAGE VARCHAR(65535),
    SOURCE_FILE VARCHAR(512),
    INGESTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
