-- LogSense AI: Cortex Search Service
-- Creates a semantic search service over parsed log messages.

USE DATABASE KAFKA_LOGS;
USE SCHEMA RAW;

CREATE OR REPLACE CORTEX SEARCH SERVICE LOG_SEARCH_SERVICE
  ON MESSAGE
  ATTRIBUTES APP_NAME, LOG_LEVEL, COMPONENT
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '1 minute'
  EMBEDDING_MODEL = 'snowflake-arctic-embed-m-v1.5'
  AS (
    SELECT MESSAGE, APP_NAME, LOG_LEVEL, COMPONENT
    FROM KAFKA_LOGS.RAW.PARSED_LOGS
    WHERE MESSAGE IS NOT NULL
  );
